### ISSUE TITLE
有没有可能增加发声的选项？

### ISSUE THREAD

**Issue by zhl111** [gamer-ai/eletypes-frontend#35]
如题

**Comment by MUYANGGUO** [comment]
@zhl111 

> 如题

感谢建议，键盘音还是词卡的发音功能？

**Comment by MUYANGGUO** [comment]
@zhl111 

> 词卡，键盘音已经很好了

youdao dict 老的public api似乎还是可以用的，也是这个发音api的首选。但是主要问题是超过limit会被禁。可以试试看。

**Comment by MUYANGGUO** [comment]
@zhl111 已添加发音功能。欢迎继续issue改进方向。目前希望添加customize的发音选项。（美音，英音等）
